site_name:           Julia_docs_test
repo_url:            https://github.com/nbavafa/Julia_docs_test
site_description:    Description!
site_author:         Nick
theme:               minimal

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
 

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Main Section:
  - sec/test.md
  
